# Generated by Django 4.2.23 on 2025-09-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/'),
        ),
    ]
