# Generated by Django 4.2.16 on 2025-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom'],
            },
        ),
    ]
