# Generated by Django 4.2.16 on 2025-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='frais_livraison',
            field=models.PositiveIntegerField(default=0, verbose_name='Frais de livraison (Ar)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.PositiveIntegerField(verbose_name="Prix d'achat (Ar)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.PositiveIntegerField(verbose_name='Prix de vente (Ar)'),
        ),
    ]
