# Generated by Django 4.2.16 on 2025-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='frais_livraison',
        ),
        migrations.AddField(
            model_name='article',
            name='livraison',
            field=models.CharField(choices=[('Payante', 'Payante'), ('Gratuite', 'Gratuite')], default='Payante', max_length=10, verbose_name='Frais de livraison'),
        ),
    ]
