# Generated by Django 4.2.23 on 2025-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_taille_couleur_categorie_article_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence'),
        ),
    ]
