# Generated by Django 4.2.16 on 2025-05-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pu', models.PositiveIntegerField(verbose_name='Prix unitaire')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('montant', models.PositiveIntegerField()),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('libelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.plandescomptes')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.caisse')),
            ],
        ),
    ]
