# Generated by Django 4.2.16 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0003_charge_created_at_charge_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
