# Generated by Django 4.2.16 on 2025-05-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'achat")),
                ('num_facture', models.TextField(blank=True, null=True, verbose_name='N° Facture')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.PositiveIntegerField(verbose_name='Prix Unitaire (Ar)')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant total (Ar)')),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_achats', to='achats.achat')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
