# Generated by Django 4.2.16 on 2025-05-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_frais_livraison_and_more'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneachat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_achats', to='articles.article'),
        ),
    ]
