# Generated by Django 4.2.16 on 2025-05-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('achats', '0002_alter_ligneachat_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.caisse'),
        ),
    ]
