# Generated by Django 4.2.16 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_achat_created_at_achat_created_by_achat_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
