# Generated by Django 4.2.16 on 2025-05-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_frais_livraison_and_more'),
        ('ventes', '0002_remove_commande_contact_remove_commande_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='articles.article'),
        ),
    ]
