# Generated by Django 4.2.16 on 2025-05-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ventes', '0005_alter_commande_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='page_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.pages'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
