# Generated by Django 4.2.16 on 2025-05-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ventes', '0006_commande_page_fk_alter_commande_numero_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='page_fk',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.pages'),
        ),
    ]
