# Generated by Django 4.2.16 on 2025-05-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_alter_commande_page_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='page',
        ),
    ]
