# Generated by Django 4.2.16 on 2025-05-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_remove_commande_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='page_fk',
            new_name='page',
        ),
    ]
