# Generated by Django 4.2.16 on 2025-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0014_remove_vente_remarque_commande_remarque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date',
            new_name='date_commande',
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('OK', 'OK'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('OK', 'OK'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='en_attente', max_length=20),
        ),
    ]
