# Generated by Django 4.2.16 on 2025-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0015_rename_date_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livreur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('OK', 'OK'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('OK', 'OK'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='En attente', max_length=20),
        ),
    ]
