# Generated by Django 4.2.16 on 2025-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0017_alter_commande_frais_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='frais_livreur',
            field=models.PositiveIntegerField(blank=True, default=3000, null=True),
        ),
    ]
