# Generated by Django 4.2.16 on 2025-05-17 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0021_alter_commande_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Planifiée', 'Planifiée'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Planifiée', 'Planifiée'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='En attente', max_length=20),
        ),
    ]
