# Generated by Django 4.2.16 on 2025-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0025_commande_paiement_frais_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
