# Generated by Django 4.2.23 on 2025-09-13 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0033_alter_lignecommande_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cours_devise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_debut_prestation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_fin_prestation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='impot_synthetique',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
