# Generated by Django 4.2.23 on 2025-09-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_pages_type'),
        ('ventes', '0034_commande_cours_devise_commande_date_debut_prestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiement_ventes', to='common.caisse'),
        ),
    ]
