# Generated by Django 4.2.16 on 2025-05-20 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_pages_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.caisse')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.pages')),
            ],
        ),
    ]
