# Generated by Django 4.2.16 on 2025-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='montant',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
