# Generated by Django 4.2.16 on 2025-06-07 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_pages_logo'),
        ('caisses', '0002_versement_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('caisse_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree', to='common.caisse')),
                ('caisse_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie', to='common.caisse')),
            ],
        ),
    ]
