# Generated by Django 4.2.16 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0004_mouvementcaisse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='versement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
