# Generated by Django 4.2.16 on 2025-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('precision_lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
