# Generated by Django 4.2.16 on 2025-05-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='lieu',
        ),
    ]
