# Generated by Django 4.2.16 on 2025-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_adresse_client_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lieu',
        ),
    ]
