# Generated by Django 4.2.16 on 2025-05-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_rename_fraislivraison_livraison'),
        ('clients', '0003_remove_client_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.livraison'),
        ),
    ]
