# Generated by Django 4.2.16 on 2025-06-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_alter_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_publication', models.CharField(choices=[('publié', 'Publié'), ('modifié', 'Modifié'), ('supprimé', 'Supprimé')], default='publié', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('date_debut', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('page_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_page', models.URLField(blank=True, null=True)),
                ('activite_produits', models.CharField(max_length=255)),
                ('personne_de_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_profil', models.URLField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('rcs', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fokontany', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('cin_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('date_cin', models.DateField(blank=True, null=True)),
                ('lieu_cin', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
