# Generated by Django 4.2.16 on 2025-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='activite_produits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
