# Generated by Django 4.2.23 on 2025-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_created_by_alter_client_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference_client',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
