# Generated by Django 4.2.16 on 2025-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
