# Generated by Django 4.2.16 on 2025-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_vente_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='numero_facture',
            new_name='numero_proforma',
        ),
        migrations.AddField(
            model_name='vente',
            name='numero_facture',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
