# Generated by Django 4.2.16 on 2025-05-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='precision_lieu',
        ),
    ]
