# Generated by Django 4.2.16 on 2025-05-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_frais_livraison_and_more'),
        ('ventes', '0003_alter_lignecommande_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commandes', to='ventes.commande'),
        ),
    ]
