# Generated by Django 4.2.16 on 2025-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_lignecommande_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
