# Generated by Django 4.2.16 on 2025-05-09 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ventes', '0009_rename_page_fk_commande_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('vendue', 'Vendue'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.PositiveIntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.caisse')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='ventes.commande')),
            ],
        ),
    ]
