# Generated by Django 4.2.16 on 2025-05-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_commande_statut_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='caisse',
            new_name='paiement',
        ),
    ]
