# Generated by Django 4.2.16 on 2025-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_rename_caisse_vente_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ok', 'OK'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ok', 'OK'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20),
        ),
    ]
