# Generated by Django 4.2.16 on 2025-05-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
        ('ventes', '0012_remove_commande_statut_commande_statut_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.livreur'),
        ),
    ]
