# Generated by Django 4.2.16 on 2025-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0013_commande_date_livraison_commande_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='remarque',
        ),
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('ok', 'OK'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('ok', 'OK'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20),
        ),
    ]
