# Generated by Django 4.2.16 on 2025-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0016_commande_frais_livreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='frais_livreur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
