# Generated by Django 4.2.16 on 2025-05-15 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0018_alter_commande_frais_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
