# Generated by Django 4.2.16 on 2025-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0019_alter_commande_date_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='frais_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.PositiveIntegerField(blank=True, default=3000, null=True),
        ),
    ]
