# Generated by Django 4.2.16 on 2025-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0020_remove_lignecommande_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='frais_livraison',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='frais_livreur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
