# Generated by Django 4.2.16 on 2025-05-19 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0022_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
