# Generated by Django 4.2.16 on 2025-05-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0023_alter_vente_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='date',
            new_name='date_encaissement',
        ),
    ]
