# Generated by Django 4.2.16 on 2025-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0024_rename_date_vente_date_encaissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paiement_frais_livreur',
            field=models.CharField(choices=[('Payée', 'Payée'), ('Non payée', 'Non payée'), ('N/A', 'N/A')], default='Non payée', max_length=15),
        ),
    ]
