# Generated by Django 4.2.16 on 2025-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0027_commande_created_at_commande_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
