# Generated by Django 4.2.16 on 2025-06-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0005_alter_caisse_created_by_alter_caisse_deleted_by_and_more'),
        ('ventes', '0030_alter_commande_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='page',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_commandes', to='common.pages'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_livraison',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Planifiée', 'Planifiée'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée'), ('Supprimée', 'Supprimée')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_vente',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Planifiée', 'Planifiée'), ('Payée', 'Payée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée'), ('Supprimée', 'Supprimée')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_deleted_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_ventes', to='common.caisse'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
