# Generated by Django 4.2.16 on 2025-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0031_alter_commande_created_by_alter_commande_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='prix_achat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
