# Generated by Django 4.2.16 on 2025-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0032_lignecommande_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_achat',
            field=models.PositiveIntegerField(),
        ),
    ]
