# Generated by Django 4.2.16 on 2025-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Ville', 'Ville'), ('Périphérie', 'Périphérie'), ('Super-périphérie', 'Super-périphérie'), ('Province', 'Province')], max_length=20)),
                ('frais', models.PositiveIntegerField()),
            ],
        ),
    ]
