# Generated by Django 4.2.16 on 2025-05-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_fraislivraison'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FraisLivraison',
            new_name='Livraison',
        ),
    ]
