# Generated by Django 4.2.16 on 2025-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_rename_fraislivraison_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='type',
            field=models.CharField(choices=[('Employé', 'Employé'), ('Prestataire', 'Prestataire')], default='Employé', max_length=20),
        ),
    ]
