# Generated by Django 4.2.16 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_livraison_created_at_livraison_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
