# Generated by Django 4.2.16 on 2025-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_alter_livraison_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='frais',
            new_name='frais_livraison',
        ),
        migrations.AddField(
            model_name='livraison',
            name='frais_livreur',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
