# Generated by Django 4.2.16 on 2025-05-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entrees', models.PositiveIntegerField(default=0)),
                ('sorties', models.PositiveIntegerField(default=0)),
                ('stock_final', models.IntegerField(editable=False)),
                ('inventaire_reel', models.IntegerField(blank=True, help_text='Valeur physique constatée lors d’un inventaire', null=True)),
                ('ecart_inventaire', models.IntegerField(blank=True, help_text='Différence entre le stock théorique et le stock réel', null=True)),
                ('storie', models.CharField(blank=True, help_text='Motif du mouvement : achat, vente, régularisation...', max_length=100, verbose_name='Historique / Motif')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
