# Generated by Django 4.2.16 on 2025-05-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_frais_livraison_and_more'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajustement', models.IntegerField(verbose_name='Ajustement manuel')),
                ('date', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='articles.article')),
            ],
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
    ]
