# Generated by Django 4.2.16 on 2025-05-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_inventaire_delete_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='ajustement',
            field=models.IntegerField(default=0, verbose_name='Ajustement quantité'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='date',
            field=models.DateField(verbose_name="Date d'inventaire"),
        ),
    ]
